name: Pages
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write # needed to deploy to Pages
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Demo
        run: npm run build
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.4
