#
# This workflow will run all the normal static tests (linting, unit, etc.) and
# make sure the build completes successfully.
#

name: test

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
